---
- name: Configure vESX
  hosts: localhost
  gather_facts: False
  vars_files:
    - ../answerfile.yml
  tasks:
    - name: Add ESXi Host to VCSA
      vmware_host:
        hostname: "{{ vcenter.ip }}"
        username: "{{ vcenter.user }}"
        password: "{{ vcenter.password }}"
        datacenter_name: "{{ vcenter.datacenter }}"
        validate_certs: false
        cluster_name: "{{ item.value.cluster }}"
        esxi_hostname: "{{ item.value.ip }}"
        esxi_username: "root"
        esxi_password: "VMware1!"
        state: present
      with_dict: "{{ vESX }}"

