---
- name: Deploy Nested vESX VMs
  hosts: localhost
  gather_facts: False
  become: yes
  vars_files:
    - ../answerfile.yml
  tasks:
    - name: Deploy Nested vESXi VMs at site1
      nestedESXi:
        vcenter: "{{ vc_mng.ip }}"
        vcenter_user: "{{ vc_mng.user }}"
        vcenter_passwd: "{{ vc_mng.password }}" 
        datastore: "{{ physicalESX.datastore }}"
        mgmtportgroup: "{{ vc_mng.mgmtportgroup }}"
        transportportgroup: "{{ vc_mng.transportportgroup }}"
        vmotionportgroup: "{{ vc_mng.vmotionportgroup }}"
        vmname: "{{ item.key }}"
        cluster: "{{ item.value.mng_cluster }}"
        cpucount: "{{ item.value.cpu }}"
        memory: "{{ item.value.ram }}"
        hdd: "{{ item.value.hdd }}"
        isopath: "ISO/customesxv.iso"
      with_dict: "{{ vESX }}"
      async: 7200
      poll: 0
      register: deployment
    - name: Wait 3 seconds before start checking wheter the hosts are ready
      pause: seconds=3
    - name: Result check for deployment
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: job_result
      with_items: "{{ deployment.results }}"
    - name: Create a mark if there is a new vESX to deploy
      file: path=/tmp/newESXi state=touch owner=root group=root mode=0555
      when: item.stat is not defined
      with_items: "{{ job_result.results }}"
    - stat: path=/tmp/newESXi
      register: newESXi
    - name: Wait 15 minutes before start checking wheter the hosts are ready
      pause: minutes=15
      when: newESXi.stat.exists == True
    - name: Delete the temporary mark
      file: path=/tmp/newESXi state=absent
    - name: Result check for deployment
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      with_items: "{{ deployment.results }}"
      retries: 20
  tags: nestedESX

